language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-dist

script:
  - bin/phpunit -c tests/

notifications:
  email:
    - gediminas.morkevicius@gmail.com
    - developers@atlantic18.com
